# Generated by Django 3.1.2 on 2020-10-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='meter_number',
            new_name='term_number',
        ),
    ]
