# Generated by Django 3.1.2 on 2020-10-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0002_auto_20201014_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz',
            new_name='term',
        ),
    ]
