# Generated by Django 3.1.2 on 2020-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0003_auto_20201014_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
