# Generated by Django 3.0.5 on 2020-10-26 00:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0005_auto_20201025_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=250, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=250, null=True)),
                ('incorrect_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8)),
            ],
        ),
    ]
