# Generated by Django 3.0.5 on 2020-10-26 01:10

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0006_quizquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='incorrect_answers',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8),
        ),
    ]
