# Generated by Django 3.0.5 on 2020-10-26 13:35

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ContentManager', '0007_auto_20201026_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='newModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myatr', models.CharField(blank=True, max_length=250, null=True)),
                ('list_answers', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=4)),
            ],
        ),
    ]
